# saper.wisnia.dev — przekierowanie na stronę główną (arcade usunięte)
server {
    server_name saper.wisnia.dev;

    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/saper.wisnia.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/saper.wisnia.dev/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://wisnia.dev;
}

server {
    listen 80;
    listen [::]:80;
    server_name saper.wisnia.dev;
    return 301 https://wisnia.dev;
}
